
# import = ["~/.config/alacritty/themes/tokyo-night.toml"]
# import = ["~/.config/alacritty/themes/kanagawa-dragon.toml"]
import = ["~/.config/alacritty/catppuccin-mocha.toml"]

[font]
size = 12

[font.normal]
family = "JetBrainsMono Nerd Font"

[window]
decorations = "none"

[window.padding]
x = 7
y = 0
