
[font]
size = 16

[font.normal]
#family = "JetBrainsMono Nerd Font"
family = "DankMono Nerd Font"

[colors]
#background = "#14161b"

[window]
decorations = "none"
option_as_alt = "OnlyRight"

[window.padding]
x = 7
y = 0

[general]

#import = ["~/.config/alacritty/themes/tokyo-night.toml"]
import = ["~/.config/alacritty/themes/tokyonight_night.toml"]
# import = ["~/.config/alacritty/themes/kanagawa-dragon.toml"]
# import = ["~/.config/alacritty/catppuccin-mocha.toml"]
